<?php
/*
AUTHOR:- RITHUNAND [BENCHAMXD]
CHANNEL:- @INDUSBOTS 
THIS REPO IS LICENCED WITH GENERAL PUBLIC LICENSE VERSION:3.0
(c) RITHUNAND K
*/
$TG_BOT_TOKEN = "1841774863:AAEz1VgByc48-zq3pp0SrUtYY446Ah7EZDk";
$BOT_NAME = "VC Bot";
$BOT_USERNAME = "@vclktBot";

?>
